# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4d14ef52954cbe9c6eddc3982a07ed36"
name = "project app"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobjects,write_metaobject_definitions"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

# QR CODE STUFF
[metaobjects.app.qrcode]
name = "QR Code"
description = "QR Codes that link to products"
  [metaobjects.app.qrcode.access]
  admin = "merchant_read_write"

[metaobjects.app.qrcode.fields.title]
name = "Title"
type = "single_line_text_field"
required = true

[metaobjects.app.qrcode.fields.description]
name = "Description"
type = "multi_line_text_field"

[metaobjects.app.qrcode.fields.product]
name = "Product"
type = "product_reference"

[metaobjects.app.qrcode.fields.product_variant]
name = "Product Variant"
type = "variant_reference"

[metaobjects.app.qrcode.fields.destination]
name = "destination"
type = "single_line_text_field"

[metaobjects.app.qrcode.fields.scan]
name = "scans"
type = "number_integer"


# COMMISSION MARKER METAFIELDS
[product.metafields.app.commission]
type = "json"
name = "Commission"
description = "Commission configuration for this product"

  [product.metafields.app.commission.access]
  admin = "merchant_read_write"

# COMMISSION PARTNER METAOBJECT
[metaobjects.app.partner]
name="Partner"
access.admin = "merchant_read_write"

[metaobjects.app.partner.fields.full_name]
name="Full Name"
type = "single_line_text_field"

[metaobjects.app.partner.fields.email]
name = "Email"
type = "single_line_text_field"

[metaobjects.app.partner.fields.active]
name = "Active"
type = "boolean"

[metaobjects.app.partner.fields.notes]
name = "Notes"
type = "multi_line_text_field"
